### ISSUE TITLE
FR: Pull variables into styling

### ISSUE THREAD

**Issue by i-am-abell** [mdelobelle/obsidian_supercharged_links#110]
I'm trying to include an "emoji" attribute for some notes that would replace the file icon in the left sidebar with that specific emoji. I don't think this is currently achievable, but it would be really helpful for sifting through large lists of notes.
![2022-05-10_13-59-01](https://user-images.githubusercontent.com/7960991/167692849-c83f131b-e6d8-43d9-b498-903ca68ebb54.png)

**Comment by HEmile** [comment]
I think this does what you want? Make sure to add emoji to the 'Target attributes' in the Supercharged Links settings.
```css
.data-link-icon[data-link-emoji]::before {
    content: attr(data-link-emoji);
}
```
