### ISSUE TITLE
Can Supercharged Superscripts be added to Style settings? 

### ISSUE THREAD

**Issue by brimwats** [mdelobelle/obsidian_supercharged_links#120]
I use superscripts on top of supercharged icons for additional information. Here's the CSS I use, can it be added?

Here's an example

```css
.data-link-icon[data-link-ThingType*="Event" i]::before{
    content: "📆";
    font-size: smaller;
}

/*         MTWRFSU Day Indicators for Daily Note             */
.data-link-icon[data-link-Weekday*="Mon" i]::after{
    content: "ɱ";
    font-size: x-small;
    vertical-align: super;
                font-weight: 600;
                color: #268bd2;
            }
            .data-link-icon[data-link-Weekday*="Tue" i]::after{
                content: "Ƭ";
                font-size: x-small;
                vertical-align: super;
                font-weight: 600;
                color: #268bd2;
                
            }
            .data-link-icon[data-link-Weekday*="Wed" i]::after{
                content: "Ⱳ";
                font-size: x-small;
                vertical-align: super;
                font-weight: 800;
                color: #268bd2;
            }
            .data-link-icon[data-link-Weekday*="Thu" i]::after{
                content: "Ɽ";
                font-size: x-small;
                vertical-align: super;
                font-weight: 800;
                color: #268bd2;
            }
            .data-link-icon[data-link-Weekday*="Fri" i]::after{
                content: "Ƒ";
                font-size: x-small;
                vertical-align: super;
                font-weight: 800;
                color: #268bd2;
            }
            .data-link-icon[data-link-Weekday*="Sat" i]::after{
                content: "Ş";
                font-size: x-small;
                vertical-align: super;
                font-weight: 800;
                color: #268bd2;
            }
            .data-link-icon[data-link-Weekday*="Sun" i]::after{
                content: "☼";
                font-size: x-small;
                vertical-align: super;
                font-weight: 800;
                color: #268bd2;
            }
           
```
