### ISSUE TITLE
Use frontmatter field in the link text

### ISSUE THREAD

**Issue by jvanz** [mdelobelle/obsidian_supercharged_links#141]
I think that it would be nice to allow users to use some text from the target note file frontmatter in the link text. For example, consider the following note:

```
---
author: Nobody
---
# Note
...
```

In another note, the link for above note could be shown as:

As we can in the note from [Nobody]()...

**Comment by HEmile** [comment]
I think you can already achieve this with your own CSS, but I'm not sure. You could use the CSS content property alongside (I think) `attr(data-link-author)` or something like that. 

An example I have in my configuration (which I admittedly never use)
```css
.data-link-icon[data-link-emoji]::before {
    content: attr(data-link-emoji);
}```

So I think this might work
```css
data-link-text[data-link-author] {
    content: attr(data-link-author);
}```

**Comment by jvanz** [comment]
Thank for the hint @HEmile ! I achieved something similar to what I described with this CSS:

```css
.workspace-tab-container .data-link-text[data-link-author]{
    visibility: hidden;
}

.workspace-tab-container .data-link-text[data-link-author]::before{
    content: attr(data-link-author);
    visibility: visible;
}
```
This still does not work all the time. But it is able to fix the issue partially. Therefore, I'm closing this issue.
