### ISSUE TITLE
Allow using icons from the Obsidian Icon folder

### ISSUE THREAD

**Issue by HEmile** [mdelobelle/obsidian_supercharged_links#187]
From Obsidian forum:

Hi. Is there any way to get Icons (from the Obsidian Icons folder that Icon Folder, Icons and Icon Shortcodes plugins use)?

If not is there any possibility of this being a future possibility? This would be really useful as these are generally far nicer than the OS emojis.

**Comment by jpbruckler** [comment]
With some work, SVG icons can be used. 

- I used https://svgencode.com/ to encode an svg from Font Awesome 
- I used this codepen to apply a filter to color the icon: https://codepen.io/sosuke/pen/Pjoqqp

```css
a.internal-link[data-link-type="ttrpg-pc"]::before{
    display: inline-block;
    content: url("data:image/svg+xml,<url encoded svg>");
    margin-right: 0.5em;
    filter: invert(44%) sepia(88%) saturate(680%) hue-rotate(153deg) brightness(94%) contrast(103%);
}
```
