### ISSUE TITLE
Can the applied styling be based on a property?

### ISSUE THREAD

**Issue by machado-t** [mdelobelle/obsidian_supercharged_links#192]
I'll try to explain it better with an example. 
Some files have the property "icon" with an emoji. Could this emoji be appended to the links using this plugin?

**Comment by machado-t** [comment]
Could this be done with CSS maybe?

**Comment by HEmile** [comment]
Yes, this can be done with css. See the examples in the README.
Something in this line should work:
```css
.data-link-icon-before[data-link-icon]::before{
    content: attr(data-link-icon)
}
```
