### ISSUE TITLE
Links aren't colored on mobile edit view

### ISSUE THREAD

**Issue by NicoNoell** [mdelobelle/obsidian_supercharged_links#232]
I'm a big fan of the supercharged Links and I use them together with the Style Settings Plugin to color my Links depending on which folder they are in. 
This works fine on Desktop, but on mobile if I'm in the edit mode and have the source view disabled, the supercharged Links don't work and I only see the default color. Otherwise it works great in both cases. 
Have I set something up the wrong way or does it simply not work on mobile (iOS if that matters)?

**Comment by NicoNoell** [comment]
Quick Fix: Defining the --link-color Attribute manually for all cases in the links.css snippet worked for me. On desktop it is ignored and on mobile use. Maybe this helps anyone in the future.

**Comment by Ravenclawer** [comment]
I am facing the same problem in obsidian 1.7.4 desktop version, could you elaborate on how to solve this problem?

**Comment by eenpadvinder** [comment]
@NicoNoell thanks for posting this, helped me a lot!

In case anyone is looking for an example. This one doesn't working in live editor on mobile:

```css
[data-link-path*="0 backlog" i] {color: var(--color-backlog) !important; }
```

This one does:

```css
[data-link-path*="0 backlog" i] {color: var(--color-backlog) !important; --link-color: var(--color-backlog) !important;}
```
