### ISSUE TITLE
Working with YAML dictionaries

### ISSUE THREAD

**Issue by Svarshick** [mdelobelle/obsidian_supercharged_links#243]
Is there way to check dictionary key-value?
I has YAML like this
```yaml
type:
    code:
         entity: interface
         another info...
```
And I would like to change link if it has keys type.code.entity == interface
