### ISSUE TITLE
Error: `Cannot read property 'links' of undefined`

### ISSUE THREAD

**Issue by selfire1** [mdelobelle/obsidian_supercharged_links#56]
Hi! Love this plugin. Somehow I run into the following error when styling links:
<img width="459" alt="Screenshot 2021-11-23 at 10 51 49" src="https://user-images.githubusercontent.com/70809675/143003361-021d3322-1d2a-4d2a-8a11-3a69850d4ee9.png">

My code is the following:
```css
[data-link-type~="Scripture"] {
    color: #BEA1A5;
}
```
Versions are `0.3.6` of Supercharged Links and `0.12.19` of Obsidian.

Thanks for your help!
