### ISSUE TITLE
Bug: Live preview does not work with markdown links

### ISSUE THREAD

**Issue by javiavid** [mdelobelle/obsidian_supercharged_links#79]
Hello, 
I have tried several things to change the color of a link that has an empty key, but I can't do it. All other options work fine for me.

Can you help me?

**Comment by HEmile** [comment]
Assuming you mean with empty key that (eg)
```
---
category:
---
```
this _might_ work (I have not tested it):
```css
[data-link-category=""]{
    color: blue;
}
```

**Comment by javiavid** [comment]
I've tried it with the default obsidian theme and turning off all plugins and it doesn't work...

**Comment by HEmile** [comment]
```css
[data-link-category="null"]{
    color: blue;
}
```
This works for me. Probably a bug though :p
