### ISSUE TITLE
[Feature Request] Option to edit font family for generated CSS in Style Settings

### ISSUE THREAD

**Issue by SlRvb** [mdelobelle/obsidian_supercharged_links#87]
Currently the plugin only generates css with only the `content: `, it would be really handy to include changing the font family so that could include encoded icon fonts for more styling options.

Something like this:
```css
:root {
    --785b-0c36-before: '';
    --785b-0c36-font-family: '';
}

div[data-id="785b-0c36"] div.setting-item-description::before,
.data-link-icon[data-link-Subject*="Technology" i]::before {
    content: var(--785b-0c36-before);
    font-family: var(--785b-0c36-font-family);
    font-weight: 10;
}


/* @settings
name: Supercharged Links
id: supercharged-links
settings:
    - 
        id: 785b-0c36
        title: Subject is Technology
        description: Example note
        type: heading
        collapsed: true
        level: 3
    - 
        id: 785b-0c36-before
        title: Prepend text
        description: Add some text, such as an emoji, before the links.
        type: variable-text
        default: ''
        quotes: true
    - 
        id: 785b-0c36-font-family
        title: Prepend text font family
        description: Add font family to use encoded Icon fonts.
        type: variable-text
        default: 'Inter'
        quotes: true
*/
```

---

Also I recommend adding `font-weight: 10` because if text is bolded, it will effect the emoji or encoded icon font.

With `font-weight: 10`:
![Obsidian_m65vXneqyz](https://user-images.githubusercontent.com/54087190/152677836-a10ec542-12e9-4e08-b112-44140c0bd914.png)

Without `font-weight: 10`:
![aV8WYulzcD](https://user-images.githubusercontent.com/54087190/152677844-b77f3434-9a3e-459d-9814-bf12ae43771c.png)
