### ISSUE TITLE
text-decoration option: none

### ISSUE THREAD

**Issue by kalmir** [mdelobelle/obsidian_supercharged_links#97]
I would like to be able to set text-decoration to none. It is not possible via Style Settings and I wasn't able to do it via a css snippet: I managed to target the element and e.g. change color but not text-decoration. I am talking about live-preview when the text is not edited.

**Comment by HEmile** [comment]
Hmm... Good point, this seems pretty buggy. The Style Settings option doesn't seem reliable. On the default theme I can do it with CSS using

```css
[data-link-tags*="#concept" i] > .cm-underline {
    text-decoration: none !important;
}
```
since the default theme targets `.cm-underline`. This modification doesn't seem to work for Primary though...

**Comment by HEmile** [comment]
For Primary, I got it to work by adding
```css
.cm-hmd-internal-link {
    text-decoration: none !important;
}

.cm-underline {
    text-decoration: underline;
}
```
